name: ship-tools-seo
on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/ship-tools-seo.yml

jobs:
  patch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - uses: actions/setup-node@v4
        with: { node-version: '20' }

      - name: Apply patch (add files, patch code, fix favicon, update package.json)
        shell: bash
        run: |
          set -euo pipefail

          mkdir -p scripts src/components/tool/utils src/components/common src/lib

          # A) Postbuild head injector
          cat > scripts/head-injector.mjs <<'EOF'
          import fs from "fs";
          import path from "path";
          import { fileURLToPath } from "url";
          import cheerio from "cheerio";
          const __dirname = path.dirname(fileURLToPath(import.meta.url));
          const DIST = path.resolve(__dirname, "..", "dist");
          const SITE = "https://omahatreecare.com";
          const clamp=(s,n)=>s.length<=n?s:s.slice(0,n-1)+"…";
          const canonicalFor = (relPath)=>{
            const p = relPath.replace(/\\/g,"/").replace(/index\.html$/i,"").replace(/\.html$/i,"");
            return p===""?`${SITE}/`:`${SITE}/${p}`;
          };
          function processFile(abs){
            const html = fs.readFileSync(abs,"utf8");
            const $ = cheerio.load(html,{decodeEntities:false});
            const rel = path.relative(DIST,abs);
            const canon = canonicalFor(rel);
            const $head = $("head"); if(!$head.length) return false;
            // title
            let title = ($("title").text()||"").trim();
            if(!title){
              const h1 = $("h1").first().text().trim();
              title = clamp(h1?`${h1} | Omaha Tree Care`:"Omaha Tree Care",60);
              $head.append(`<title>${title}</title>`);
            }
            // description
            let metaDesc = $('meta[name="description"]').attr("content")||"";
            if(!metaDesc || metaDesc.length<80){
              const h1 = $("h1").first().text().trim();
              metaDesc = clamp((h1?`${h1}. `:"")+"Free pricing & same-day quotes in Omaha & nearby cities.",155);
              if($('meta[name="description"]').length){ $('meta[name="description"]').attr("content", metaDesc); }
              else{ $head.append(`<meta name="description" content="${metaDesc}">`); }
            }
            // canonical
            if ($('link[rel="canonical"]').length) $('link[rel="canonical"]').attr("href", canon);
            else $head.append(`<link rel="canonical" href="${canon}">`);
            // OG
            const ensure=(prop,val)=>{ const sel=`meta[property="${prop}"]`;
              if($(sel).length) $(sel).attr("content",val); else $head.append(`<meta property="${prop}" content="${val}">`);
            };
            ensure("og:type","website");
            ensure("og:title", $('title').text().trim());
            ensure("og:description", $('meta[name="description"]').attr("content")||"");
            ensure("og:url", canon);
            if(!$('meta[property="og:image"]').length) ensure("og:image","/og-image.jpg");
            // favicon
            $('link[rel~="icon"]').each((_,el)=>{ const href=$(el).attr("href")||""; if(/vite\.svg/i.test(href)) $(el).remove();});
            if(!$('link[rel~="icon"]').length) $head.append('<link rel="icon" href="/favicon.ico">');
            fs.writeFileSync(abs,$.html(),"utf8"); return true;
          }
          function walk(dir, acc=[]){ for(const n of fs.readdirSync(dir)){ const p=path.join(dir,n); const st=fs.statSync(p);
            if(st.isDirectory()) walk(p,acc); else if(n.endsWith(".html")) acc.push(p);} return acc; }
          if (fs.existsSync(DIST)) {
            const pages = walk(DIST); let changed=0;
            for(const f of pages) if(processFile(f)) changed++;
            console.log(`[head-injector] processed ${changed}/${pages.length} HTML files`);
          } else {
            console.log(`[head-injector] skipped (no dist yet)`);
          }
          EOF

          # B) Small libs/components
          cat > src/lib/analytics.js <<'EOF'
          export function track(eventName, props = {}) {
            if (typeof window === "undefined" || !window.dataLayer) return;
            window.dataLayer.push({ event: eventName, ...props });
          }
          EOF

          cat > src/components/common/StickyCTA.jsx <<'EOF'
          export default function StickyCTA({ phone = "+14028123294" }) {
            return (
              <div style={{
                position: "fixed", bottom: 0, left: 0, right: 0,
                display: "flex", gap: 8, padding: 10,
                alignItems: "center", justifyContent: "space-between",
                boxShadow: "0 -2px 10px rgba(0,0,0,0.08)",
                background: "#fff", zIndex: 1000
              }}>
                <a href={`tel:${phone}`} style={{flex: 1, textAlign: "center", padding: 12, borderRadius: 12, border: "1px solid #e5e7eb"}}>Call</a>
                <a href={`sms:${phone}`} style={{flex: 1, textAlign: "center", padding: 12, borderRadius: 12, border: "1px solid #e5e7eb"}}>Text</a>
                <a href="/quote" style={{flex: 2, textAlign: "center", padding: 12, borderRadius: 12, border: "1px solid #e5e7eb"}}>Free Quote</a>
              </div>
            );
          }
          EOF

          cat > src/components/tool/utils/slugify.js <<'EOF'
          export function slugify(s = "") {
            return s.toLowerCase().trim()
              .replace(/[^a-z0-9]+/g, "-")
              .replace(/^-+|-+$/g, "");
          }
          EOF

          # C) Patch package.json safely (add cheerio + postbuild)
          node - <<'EOF'
          const fs = require('fs');
          const p = JSON.parse(fs.readFileSync('package.json','utf8'));
          p.scripts = p.scripts || {};
          p.scripts.postbuild = "node scripts/head-injector.mjs";
          if(!p.dependencies) p.dependencies = {};
          if(!(p.dependencies.cheerio || (p.devDependencies && p.devDependencies.cheerio))) {
            p.dependencies.cheerio = "^1.0.0-rc.12";
          }
          fs.writeFileSync('package.json', JSON.stringify(p,null,2));
          console.log('package.json updated');
          EOF

          # D) Patch CostEstimator.jsx to export services + helper
          node - <<'EOF'
          const fs = require('fs');
          const path = 'src/components/tool/screens/CostEstimator.jsx';
          if (fs.existsSync(path)) {
            let s = fs.readFileSync(path,'utf8');
            if (!/export const services/.test(s)) s = s.replace(/const\s+services\s*=/, 'export const services =');
            if (!/from '\.\.\/utils\/slugify'/.test(s)) s = "import { slugify } from '../utils/slugify';\n" + s;
            if (!/function getServiceBySlug/.test(s) && !/export function getServiceBySlug/.test(s)) {
              s += "\nexport function getServiceBySlug(slug){ if(!slug) return null; return services.find(x => slugify(x.name) === String(slug).toLowerCase()) || null; }\n";
            }
            fs.writeFileSync(path,s);
            console.log('Patched CostEstimator.jsx');
          } else { console.log('CostEstimator.jsx not found (skipped)'); }
          EOF

          # E) Patch TreeDiagnostic.jsx to wire SEO, deep-linking, sticky CTA
          node - <<'EOF'
          const fs = require('fs');
          const path = 'src/components/tool/TreeDiagnostic.jsx';
          if (fs.existsSync(path)) {
            let s = fs.readFileSync(path,'utf8');
            const maybePrepend = (imp)=>{ if(!s.includes(imp)) s = imp + "\n" + s; };
            maybePrepend("import StickyCTA from '../common/StickyCTA.jsx';");
            maybePrepend("import ToolSEO from './ToolSEO';");
            maybePrepend("import { slugify } from './utils/slugify';");
            maybePrepend("import { services, getServiceBySlug } from './screens/CostEstimator';");
            if (!/useState/.test(s)) maybePrepend("import { useEffect, useState } from 'react';");
            if (!/from '..\/..\/lib\/analytics'/.test(s)) maybePrepend("import { track } from '../../lib/analytics';");
            if (!/initialSelectedService/.test(s)) {
              s = s.replace(/function\s+[A-Za-z0-9_]+\s*\(/,
                match => match +
                "\n  const [initialSelectedService, setInitialSelectedService] = useState(null);\n" +
                "  useEffect(()=>{ try{ const qp=new URLSearchParams(window.location.search); const svc=getServiceBySlug(qp.get('service')); if(svc) setInitialSelectedService(svc.name);}catch(e){} },[]);\n"
              );
            }
            if (!s.includes('<ToolSEO')) s = s.replace(/return\s*\(/, m => m + "\n      <ToolSEO services={services} />");
            if (!s.includes('<StickyCTA')) s = s.replace(/\)\s*;\s*}\s*$/m, m => "      <StickyCTA />\n    " + m);
            fs.writeFileSync(path,s);
            console.log('Patched TreeDiagnostic.jsx');
          } else { console.log('TreeDiagnostic.jsx not found (skipped)'); }
          EOF

          # F) Favicon: kill vite.svg refs if exist
          for f in public/index.html index.html; do
            if [ -f "$f" ]; then
              sed -i 's#href="/vite.svg"#href="/favicon.ico"#g' "$f" || true
            fi
          done

          git add -A
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Automated: ToolSEO plumbing + head injector + deep-linking + sticky CTA + favicon fix"
            git push
          fi

      - name: Build (optional sanity) — will run injector postbuild
        if: ${{ always() }}
        run: |
          if [ -f package-lock.json ]; then npm ci; else npm i; fi
          npm run build || true
          echo "Build attempted (not failing workflow if it errors)."
